// @ts-nocheck
import * as __fd_glob_54 from "../content/docs/get-started/theming.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/get-started/installation.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/get-started/design.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/get-started/dark-mode.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/get-started/cli.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/get-started/alternatives.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/get-started/agent-skills.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/toggle-group.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/table.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/stat-card.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/spinner.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/sonner.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/social-links.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/sheet.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/settings-section.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/radio-group.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/progress.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/pagination.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/page-header.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/page-footer.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/navii-avatar.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/mode-toggle.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/login-form.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/label.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/input-group.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/icon-nav-link.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/field.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/empty-state.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/data-table.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/command.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/collapsible.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/breadcrumb.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/get-started/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "get-started/meta.json": __fd_glob_1, "components/meta.json": __fd_glob_2, }, {"index.mdx": __fd_glob_3, "components/accordion.mdx": __fd_glob_4, "components/alert-dialog.mdx": __fd_glob_5, "components/alert.mdx": __fd_glob_6, "components/avatar.mdx": __fd_glob_7, "components/badge.mdx": __fd_glob_8, "components/breadcrumb.mdx": __fd_glob_9, "components/button.mdx": __fd_glob_10, "components/card.mdx": __fd_glob_11, "components/checkbox.mdx": __fd_glob_12, "components/collapsible.mdx": __fd_glob_13, "components/command.mdx": __fd_glob_14, "components/data-table.mdx": __fd_glob_15, "components/dialog.mdx": __fd_glob_16, "components/dropdown-menu.mdx": __fd_glob_17, "components/empty-state.mdx": __fd_glob_18, "components/field.mdx": __fd_glob_19, "components/icon-nav-link.mdx": __fd_glob_20, "components/input-group.mdx": __fd_glob_21, "components/input.mdx": __fd_glob_22, "components/label.mdx": __fd_glob_23, "components/login-form.mdx": __fd_glob_24, "components/mode-toggle.mdx": __fd_glob_25, "components/navii-avatar.mdx": __fd_glob_26, "components/page-footer.mdx": __fd_glob_27, "components/page-header.mdx": __fd_glob_28, "components/pagination.mdx": __fd_glob_29, "components/popover.mdx": __fd_glob_30, "components/progress.mdx": __fd_glob_31, "components/radio-group.mdx": __fd_glob_32, "components/select.mdx": __fd_glob_33, "components/separator.mdx": __fd_glob_34, "components/settings-section.mdx": __fd_glob_35, "components/sheet.mdx": __fd_glob_36, "components/skeleton.mdx": __fd_glob_37, "components/social-links.mdx": __fd_glob_38, "components/sonner.mdx": __fd_glob_39, "components/spinner.mdx": __fd_glob_40, "components/stat-card.mdx": __fd_glob_41, "components/switch.mdx": __fd_glob_42, "components/table.mdx": __fd_glob_43, "components/tabs.mdx": __fd_glob_44, "components/textarea.mdx": __fd_glob_45, "components/toggle-group.mdx": __fd_glob_46, "components/tooltip.mdx": __fd_glob_47, "get-started/agent-skills.mdx": __fd_glob_48, "get-started/alternatives.mdx": __fd_glob_49, "get-started/cli.mdx": __fd_glob_50, "get-started/dark-mode.mdx": __fd_glob_51, "get-started/design.mdx": __fd_glob_52, "get-started/installation.mdx": __fd_glob_53, "get-started/theming.mdx": __fd_glob_54, });